// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Week6Test.Context;

namespace Week6Test.Migrations
{
    [DbContext(typeof(PolizzeContext))]
    [Migration("20210625081846_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Week6Test.Models.Client", b =>
                {
                    b.Property<string>("CF")
                        .HasMaxLength(16)
                        .HasColumnType("nchar(16)")
                        .IsFixedLength(true);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CF");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Week6Test.Models.Policy", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientCF")
                        .HasColumnType("nchar(16)");

                    b.Property<float>("InsuranceAmount")
                        .HasColumnType("real");

                    b.Property<float>("MonthlyInstallment")
                        .HasColumnType("real");

                    b.Property<DateTime>("StipulationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("policy_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Number");

                    b.HasIndex("ClientCF");

                    b.ToTable("Policy");

                    b.HasDiscriminator<string>("policy_type").HasValue("policy");
                });

            modelBuilder.Entity("Week6Test.Models.CarRCPolicy", b =>
                {
                    b.HasBaseType("Week6Test.Models.Policy");

                    b.Property<int>("Displacement")
                        .HasColumnType("int");

                    b.Property<string>("Plate")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("car_rc_policy");
                });

            modelBuilder.Entity("Week6Test.Models.LifePolicy", b =>
                {
                    b.HasBaseType("Week6Test.Models.Policy");

                    b.Property<int>("Years")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("life_policy");
                });

            modelBuilder.Entity("Week6Test.Models.TheftPolicy", b =>
                {
                    b.HasBaseType("Week6Test.Models.Policy");

                    b.Property<int>("PercentageCoverage")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("theft_policy");
                });

            modelBuilder.Entity("Week6Test.Models.Policy", b =>
                {
                    b.HasOne("Week6Test.Models.Client", "Client")
                        .WithMany("Policies")
                        .HasForeignKey("ClientCF");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Week6Test.Models.Client", b =>
                {
                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
